# -*- coding: utf-8 -*-
"""CodigoLarryFinalInvOp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jOF7Tlc5BaPtn2PvmneceM1Tk3ncWNY8
"""

# =============================================================
# SISTEMA DE INVESTIGACIÓN DE OPERACIONES — v6
# =============================================================
# Cambios v5 → v6:
#   • Prompt de extraer_nlp con ejemplo P*Q (sustitución obligatoria)
#   • Sanity check en resolver_nlp (detecta resultados absurdos)
#   • Debug print del JSON extraído para diagnóstico
#   • llm_explicacion() para respuestas más rápidas cuando hay solver
#   • REGLA DE ORO 4 en clasificador (TRANSPORTE con intermedios)
#   • Modelo de red de transporte (extraer_red_transporte)
#   • REASONING_EFFORT="medium" (3x más rápido que "high")
#   • Chunks de 300/60 + K_TEORIA=6 (mejor precisión RAG)
# =============================================================

import os, re, time, heapq, json, math
from collections import defaultdict, Counter
from dataclasses import dataclass, field
from typing import Optional

import numpy as np
import pandas as pd
import networkx as nx
import pulp
from scipy.optimize import linprog, minimize, linear_sum_assignment

from langchain_core.documents import Document
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_groq import ChatGroq
from sentence_transformers import SentenceTransformer
from supabase import create_client, Client

# =============================================================
# CONFIGURACIÓN
# =============================================================

# 🔑 API KEYS — moverlas a variables de entorno cuando puedas
GROQ_API_KEY = os.environ["GROQ_API_KEY"]
SUPABASE_URL = os.environ["SUPABASE_URL"]
SUPABASE_KEY = os.environ["SUPABASE_KEY"]

# 🧠 MODELO PRINCIPAL — razonamiento de alta calidad
MODEL_REASONING = "openai/gpt-oss-120b"      # razonamiento high — cálculos
MODEL_FAST      = "llama-3.1-8b-instant"     # clasificación rápida
REASONING_EFFORT = "medium"                    # low | medium | high

# 📚 RAG
TABLA_DOCS    = "documentos_io"     # chunks del libro Hillier
TABLA_EJERC   = "ejercicios_io"     # historial de consultas del usuario (NO usado para RAG)
MAX_CHUNKS    = 2000                # antes 500 — ahora cubre todo el libro
CHUNK_SIZE_S  = 300                 # chunks pequeños para búsqueda fina
CHUNK_OVL_S   = 60
CHUNK_SIZE_L  = 1500                # chunks grandes para contexto extendido
CHUNK_OVL_L   = 200

# 🎯 Retrieval — solo teoría del libro
K_TEORIA      = 6    # chunks del libro Hillier
UMBRAL_CACHE  = 0.99 # casi-exacto: solo evita re-resolver la MISMA pregunta consecutiva

# 🔁 Self-consistency
NUM_MUESTRAS  = 3    # número de muestreos para votación cuando NO hay solver numérico

# =============================================================
# CLIENTES
# =============================================================

supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)

print("⏱️  Cargando modelo de embeddings...")
embedding_model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")
print("✅ Embeddings listos (384 dims)")


def llm_reasoning(temperature: float = 0.1) -> ChatGroq:
    """LLM principal con razonamiento. Usar para resolver problemas."""
    return ChatGroq(
        model=MODEL_REASONING,
        temperature=temperature,
        api_key=GROQ_API_KEY,
        reasoning_effort=REASONING_EFFORT,
        max_tokens=8192,
    )

def llm_explicacion(temperature: float = 0.1) -> ChatGroq:
    """LLM rápido para explicar soluciones ya calculadas por solver."""
    return ChatGroq(
        model=MODEL_FAST,  # llama-3.1-8b-instant
        temperature=temperature,
        api_key=GROQ_API_KEY,
        max_tokens=4096,
    )


def llm_fast(temperature: float = 0.0) -> ChatGroq:
    """LLM rápido y barato. Usar para clasificación y parseo."""
    return ChatGroq(
        model=MODEL_FAST,
        temperature=temperature,
        api_key=GROQ_API_KEY,
    )


# =============================================================
# RETRY
# =============================================================

def extraer_segundos(error, default=60):
    m = re.search(r'retry in (\d+(?:\.\d+)?)\s*s', str(error), re.IGNORECASE)
    return int(float(m.group(1))) + 2 if m else default


def con_retry(fn, *args, max_intentos=6, etiqueta="op", **kwargs):
    for intento in range(1, max_intentos + 1):
        try:
            return fn(*args, **kwargs)
        except Exception as e:
            es_quota = any(x in str(e) for x in ["429", "RESOURCE_EXHAUSTED", "rate_limit"])
            if es_quota and intento < max_intentos:
                espera = extraer_segundos(e)
                print(f"⏳ [{etiqueta}] Rate limit — {intento}/{max_intentos}, esperando {espera}s")
                time.sleep(espera)
            else:
                raise
    raise RuntimeError(f"[{etiqueta}] Reintentos agotados.")


def _invoke(llm, prompt: str) -> str:
    return llm.invoke(prompt).content


# =============================================================
# UTILIDADES DE EMBEDDING
# =============================================================

def encode(texto: str) -> np.ndarray:
    """Codifica un texto a vector. Single text → 1D array."""
    if isinstance(texto, str):
        return embedding_model.encode([texto])[0]
    return embedding_model.encode(texto)


def cosine(a: np.ndarray, b: np.ndarray) -> float:
    return float(np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b) + 1e-9))


def parse_embedding(raw) -> np.ndarray:
    """Supabase puede devolver embedding como string JSON o como lista."""
    if isinstance(raw, str):
        raw = json.loads(raw)
    return np.array(raw, dtype=np.float32)


# =============================================================
# SUPABASE: tabla DOCUMENTOS (libro)
# =============================================================

def docs_count() -> int:
    res = supabase.table(TABLA_DOCS).select("id", count="exact").limit(1).execute()
    return res.count or 0


def cargar_df_docs() -> pd.DataFrame:
    print("📥 Cargando libro desde Supabase (paginado)...")
    PAGE_SIZE = 1000
    offset = 0
    all_rows = []
    while True:
        res = supabase.table(TABLA_DOCS).select("texto, embedding, pagina").range(offset, offset + PAGE_SIZE - 1).execute()
        if not res.data:
            break
        all_rows.extend(res.data)
        if len(res.data) < PAGE_SIZE:
            break
        offset += PAGE_SIZE
    if not all_rows:
        return pd.DataFrame(columns=["text", "embedding", "page"])
    df = pd.DataFrame([
        {"text": r["texto"], "embedding": parse_embedding(r["embedding"]), "page": r["pagina"]}
        for r in all_rows
    ])
    print(f"✅ {len(df)} chunks del libro cargados")
    return df


def guardar_chunks_libro(chunks_list, vectores):
    LOTE = 100
    total = len(chunks_list)
    print(f"📤 Subiendo {total} chunks del libro...")
    for i in range(0, total, LOTE):
        registros = [
            {
                "texto": c.page_content,
                "embedding": v.tolist(),
                "pagina": c.metadata.get("page"),
                "fuente": c.metadata.get("source", ""),
            }
            for c, v in zip(chunks_list[i:i+LOTE], vectores[i:i+LOTE])
        ]
        supabase.table(TABLA_DOCS).insert(registros).execute()
        print(f"   ✔ {min(i+LOTE, total)}/{total}")
    print("✅ Libro indexado en Supabase")


# =============================================================
# SUPABASE: tabla EJERCICIOS — SOLO historial de consultas
# =============================================================
# IMPORTANTE: esta tabla NO se usa para enriquecer el prompt.
# Solo guarda lo que el usuario fue preguntando, para que pueda
# revisarlo después con la opción 2 del menú.
# Cero contaminación: cada problema se resuelve desde cero.
# =============================================================

def ejercicios_count() -> int:
    res = supabase.table(TABLA_EJERC).select("id", count="exact").limit(1).execute()
    return res.count or 0


def respuesta_en_cache(pregunta: str) -> tuple[bool, Optional[str]]:
    """
    Solo evita re-resolver la MISMA pregunta consecutiva (sim >= 0.99).
    Útil cuando el usuario pega exactamente el mismo enunciado dos veces.
    NO se usa para responder problemas similares — esos se resuelven de cero.
    """
    res = supabase.table(TABLA_EJERC).select("pregunta, respuesta, embedding").order("id", desc=True).limit(200).execute()
    if not res.data:
        return False, None
    q_vec = encode(pregunta)
    mejor_sim = -1.0
    mejor_resp = None
    for row in res.data:
        try:
            vec = parse_embedding(row["embedding"])
            sim = cosine(q_vec, vec)
            if sim > mejor_sim:
                mejor_sim = sim
                mejor_resp = row["respuesta"]
        except Exception:
            continue
    if mejor_sim >= UMBRAL_CACHE:
        return True, mejor_resp
    return False, None


def guardar_ejercicio(pregunta: str, respuesta: str, tipo: str = "DESCONOCIDO"):
    """Guarda el ejercicio en el historial. NO se usa para RAG."""
    vec = encode(pregunta).tolist()
    supabase.table(TABLA_EJERC).insert({
        "pregunta": pregunta[:8000],
        "respuesta": respuesta[:16000],
        "embedding": vec,
        "tipo": tipo,
    }).execute()


# =============================================================
# CARGA DEL PDF + INDEXACIÓN
# =============================================================

def cargar_pdf(pdf_path: str) -> list[Document]:
    if not os.path.exists(pdf_path):
        print(f"❌ PDF no encontrado: {pdf_path}")
        return []

    docs = []
    print(f"📄 Cargando {os.path.basename(pdf_path)}...")
    try:
        from pypdf import PdfReader
        reader = PdfReader(pdf_path, strict=False)
        for i, page in enumerate(reader.pages):
            text = page.extract_text()
            if text and text.strip():
                docs.append(Document(page_content=text, metadata={"page": i, "source": pdf_path}))
        if docs:
            print(f"✅ pypdf: {len(docs)} páginas")
            return docs
    except Exception as e1:
        print(f"⚠️  pypdf falló ({e1}), probando pdfminer...")

    try:
        from pdfminer.high_level import extract_pages
        from pdfminer.layout import LTTextContainer
        for i, layout in enumerate(extract_pages(pdf_path)):
            texto = "".join(el.get_text() for el in layout if isinstance(el, LTTextContainer))
            if texto.strip():
                docs.append(Document(page_content=texto, metadata={"page": i, "source": pdf_path}))
        print(f"✅ pdfminer: {len(docs)} páginas")
    except Exception as e2:
        print(f"❌ pdfminer también falló: {e2}")
    return docs


def chunks_jerarquicos(docs: list[Document]) -> list[Document]:
    """
    Chunking de dos niveles. El primer pase corta fino para búsqueda,
    luego cada chunk lleva como metadato el chunk grande de su entorno.
    """
    splitter_pequeno = RecursiveCharacterTextSplitter(
        chunk_size=CHUNK_SIZE_S, chunk_overlap=CHUNK_OVL_S,
        separators=["\n\n", "\n", ".", " "],
    )
    return splitter_pequeno.split_documents(docs)


def asegurar_libro_indexado(pdf_path: str) -> pd.DataFrame:
    if docs_count() > 0:
        return cargar_df_docs()

    docs = cargar_pdf(pdf_path)
    if not docs:
        return pd.DataFrame(columns=["text", "embedding", "page"])

    chunks = chunks_jerarquicos(docs)
    print(f"✅ {len(chunks)} chunks creados (objetivo: {MAX_CHUNKS})")
    total = min(MAX_CHUNKS, len(chunks))
    if len(chunks) > MAX_CHUNKS:
        print(f"⚠️  Truncando a {MAX_CHUNKS} chunks (sube MAX_CHUNKS si quieres todo)")

    textos = [c.page_content for c in chunks[:total]]
    print(f"🔢 Generando embeddings de {total} chunks...")
    vectores = embedding_model.encode(textos, batch_size=64, show_progress_bar=True)
    guardar_chunks_libro(chunks[:total], vectores)

    return pd.DataFrame([
        {"text": c.page_content, "embedding": v, "page": c.metadata.get("page")}
        for c, v in zip(chunks[:total], vectores)
    ])


def buscar_teoria(query: str, df: pd.DataFrame, k: int = K_TEORIA) -> str:
    """Top-k chunks del libro, usando producto punto (asume embeddings normalizados o no — funciona)."""
    if df.empty:
        return ""
    q_vec = encode(query)
    df_tmp = df.copy()
    df_tmp['score'] = df_tmp['embedding'].apply(lambda x: cosine(q_vec, x))
    top = df_tmp.sort_values('score', ascending=False).head(k)
    return "\n---\n".join(top['text'].tolist())


# =============================================================
# CLASIFICADOR DE TIPO DE PROBLEMA
# =============================================================

TIPOS_VALIDOS = [
    "LP", "IP", "TRANSPORTE", "ASIGNACION", "FLUJO_MAX",
    "RUTA_CORTA", "PERT_CPM", "COLAS_MM1", "COLAS_MMC", "EOQ", "NLP", "OTRO",
]


def clasificar_problema(pregunta: str) -> str:
    """
    Clasificador con 2 capas:
    1. Heurísticas por palabras clave (rápido, casos obvios)
    2. LLM con razonamiento (casos ambiguos)
    """
    pregunta_lower = pregunta.lower()

    # ============ CAPA 1: Heurísticas por palabras clave ============

    # M/M/c (>= 2 servidores): aparece "c servidores", "c=2", "varios servidores"
    if (re.search(r'\b(c\s*=\s*[2-9]|[2-9]\s*servidores|servidores en paralelo|múltiples servidores)\b', pregunta_lower)
        and re.search(r'(lambda|tasa de llegada)', pregunta_lower)):
        return "COLAS_MMC"

    # M/M/1: tiene lambda Y mu (con o sin "tasa")
    tiene_lambda = bool(re.search(r'(lambda|tasa de llegada|λ)', pregunta_lower))
    tiene_mu = bool(re.search(r'(\bmu\b|tasa de servicio|μ)', pregunta_lower))
    if tiene_lambda and tiene_mu:
        print("   🎯 Clasificado por heurística (lambda + mu detectados)")
        return "COLAS_MM1"

    # EOQ: palabras de inventario
    if re.search(r'(eoq|cantidad económica|punto de reorden|costo de pedido|costo de mantenimiento|demanda anual)', pregunta_lower):
        return "EOQ"

    # PERT/CPM
    if re.search(r'(pert|cpm|ruta crítica|actividades.*duración|predecesores|cronograma)', pregunta_lower):
        return "PERT_CPM"

    # Flujo máximo
    if re.search(r'(flujo máximo|maximum flow|ford.?fulkerson|capacidad de.*arco)', pregunta_lower):
        return "FLUJO_MAX"

    # Asignación
    if re.search(r'(asignar.*tareas|matriz.*asignación|húngaro|hungarian)', pregunta_lower):
        return "ASIGNACION"

    # ============ CAPA 2: LLM para casos ambiguos ============

    llm = ChatGroq(
        model=MODEL_REASONING,
        temperature=0.0,
        api_key=GROQ_API_KEY,
        reasoning_effort="medium",   # subido de "low"
        max_tokens=1024,             # subido de 512
    )
    prompt = f"""Clasifica el siguiente problema de Investigación de Operaciones en UNA sola categoría.

Categorías válidas:
- LP             : Programación lineal CONTINUA. La función objetivo y TODAS las restricciones
                   son SUMAS de términos a*x_i (constante por variable). Variables reales.
- IP             : Igual que LP pero variables ENTERAS o BINARIAS.
- TRANSPORTE     : Orígenes con oferta, destinos con demanda, matriz de costos de envío.
- ASIGNACION     : Asignar n agentes a n tareas (matriz cuadrada de costos).
- FLUJO_MAX      : Red dirigida con capacidades en arcos, fuente y sumidero.
- RUTA_CORTA     : Ruta más corta entre dos nodos en grafo con pesos.
- PERT_CPM       : Cronograma de proyecto con actividades, predecesores y duraciones.
- COLAS_MM1      : Cola con 1 servidor. Suele dar lambda (tasa de llegada) y mu (tasa de servicio).
                   Si menciona "tasa de llegada" + "tasa de servicio" → es M/M/1.
- COLAS_MMC      : Cola con c >= 2 servidores en paralelo.
- EOQ            : Cantidad económica de pedido / ROP / inventarios. Suele dar D, S, H, lead time.
- NLP            : Programación NO lineal. Usa esta categoría si aparece CUALQUIERA de:
                   * producto de variables (xy, x*y, x·y, P*Q donde P depende de Q)
                   * potencias (x², x^2, x³, x^n con n != 1)
                   * función de demanda P(Q) que multiplica por Q (genera Q² implícito)
                   * cocientes (1/x, a/x, x/y)
                   * raíces (sqrt(x), x^0.5)
                   * funciones (sin, cos, log, ln, exp)
                   * restricciones tipo xy = constante, x²+y² = r
                   * problemas con áreas (m²) o volúmenes (m³)
- OTRO           : No encaja en ninguna anterior.

REGLA DE ORO 1: si el enunciado contiene productos de variables, áreas, volúmenes,
divisiones, raíces, derivadas o funciones no lineales → ES NLP, NUNCA LP.

REGLA DE ORO 2: si la función objetivo es Beneficio = Ingresos - Costo donde
Ingresos = P*Q y P depende linealmente de Q (ej. P = 100 - 0.01Q), entonces el
producto P*Q genera Q² → ES NLP.

REGLA DE ORO 3: si solo hay lambda y mu sin más restricciones, es COLAS_MM1
(no OTRO).

REGLA DE ORO 4: si el enunciado menciona "enviar N unidades de X a Y" con costos
de transporte y NODOS INTERMEDIOS ("pasando por", "vía", "transbordo"),
ES TRANSPORTE (no RUTA_CORTA). RUTA_CORTA es para encontrar el camino más corto
en un grafo, sin restricción de cantidad de flujo.

Razona brevemente y responde con UNA sola palabra de la lista en la última línea.

PROBLEMA:
{pregunta}
"""
    try:
        raw = con_retry(_invoke, llm, prompt, etiqueta="clasif").strip().upper()
        for linea in reversed(raw.splitlines()):
            linea = linea.strip()
            palabras = re.findall(r'[A-Z_]+', linea)
            for p in palabras:
                if p in TIPOS_VALIDOS:
                    return p
        return "OTRO"
    except Exception as e:
        print(f"⚠️  Clasificador falló: {e}")
        return "OTRO"


# =============================================================
# SOLVERS
# =============================================================

# ---------- LP / IP ----------

def extraer_lp_json(pregunta: str) -> Optional[dict]:
    """Intenta extraer estructura LP. Devuelve dict o None."""
    llm = llm_fast(temperature=0.0)
    prompt = f"""Analiza el siguiente enunciado de Programación Lineal/Entera y devuelve ÚNICAMENTE un JSON válido sin texto adicional.

Formato exacto:
{{
  "es_lp": true,
  "objetivo": "maximizar" | "minimizar",
  "variables": ["x1", "x2", ...],
  "coeficientes_c": [c1, c2, ...],
  "A_ub": [[a11, a12, ...], ...] | null,
  "b_ub": [b1, ...] | null,
  "A_geq": [[a11, a12, ...], ...] | null,   // restricciones >=
  "b_geq": [b1, ...] | null,
  "A_eq": [[a11, a12, ...], ...] | null,
  "b_eq": [b1, ...] | null,
  "bounds": [[0, null], ...],
  "nombres_restricciones": ["nombre1", ...],
  "enteras": false  // true si las variables deben ser enteras
}}

REGLAS CRÍTICAS:
- TODAS las filas de A_ub, A_geq, A_eq deben tener EXACTAMENTE el mismo número de elementos que coeficientes_c.
- El número de filas en A_ub debe igualar la longitud de b_ub. Igual para A_geq/b_geq y A_eq/b_eq.
- bounds debe tener tantos elementos como coeficientes_c.
- Si el problema tiene productos de variables (xy, x*y), cocientes (1/x, a/x), potencias (x²),
  raíces, áreas/volúmenes implícitos o funciones no lineales: NO ES LP. Devuelve {{"es_lp": false}}.
- Si la única restricción es de tipo xy = constante: NO ES LP.

Si NO es LP/IP responde: {{"es_lp": false}}

ENUNCIADO:
{pregunta}
"""
    try:
        raw = con_retry(_invoke, llm, prompt, etiqueta="parse-LP")
        raw = re.sub(r"```json|```", "", raw).strip()
        d = json.loads(raw)
        if not d.get("es_lp"):
            return None
        if not validar_estructura_lp(d):
            print("⚠️  Extractor LP devolvió estructura inconsistente — descartado")
            return None
        return d
    except Exception as e:
        print(f"⚠️  Parser LP falló: {e}")
        return None


def validar_estructura_lp(lp: dict) -> bool:
    """Valida que las dimensiones del JSON sean consistentes con scipy.linprog."""
    c = lp.get("coeficientes_c")
    if not c or not isinstance(c, list) or len(c) == 0:
        return False
    n = len(c)

    for clave_A, clave_b in [("A_ub", "b_ub"), ("A_geq", "b_geq"), ("A_eq", "b_eq")]:
        A = lp.get(clave_A)
        b = lp.get(clave_b)
        if A is None and b is None:
            continue
        if A is None or b is None:
            return False
        if not isinstance(A, list) or not isinstance(b, list):
            return False
        if len(A) != len(b):
            return False
        for fila in A:
            if not isinstance(fila, list) or len(fila) != n:
                return False

    bounds = lp.get("bounds")
    if bounds is not None and len(bounds) != n:
        return False

    # Debe tener al menos UNA restricción
    if not any(lp.get(k) for k in ("A_ub", "A_geq", "A_eq")):
        return False

    return True


def resolver_lp_continuo(lp: dict) -> str:
    """Resuelve con scipy.linprog. Genera reporte tipo human-readable."""
    c = lp["coeficientes_c"]
    n = len(c)
    es_max = lp.get("objetivo", "maximizar").lower().startswith("max")
    c_scipy = [-v for v in c] if es_max else c

    # Combinar A_ub con A_geq (geq se convierte multiplicando por -1)
    A_ub = list(lp.get("A_ub") or [])
    b_ub = list(lp.get("b_ub") or [])
    if lp.get("A_geq"):
        for fila, rhs in zip(lp["A_geq"], lp["b_geq"]):
            A_ub.append([-x for x in fila])
            b_ub.append(-rhs)

    A_ub_np = np.array(A_ub) if A_ub else None
    b_ub_np = np.array(b_ub) if b_ub else None
    A_eq_np = np.array(lp["A_eq"]) if lp.get("A_eq") else None
    b_eq_np = np.array(lp["b_eq"]) if lp.get("b_eq") else None

    bounds = lp.get("bounds") or [(0, None)] * n
    bounds_scipy = [(b[0], b[1]) for b in bounds]

    try:
        r = linprog(
            c=c_scipy, A_ub=A_ub_np, b_ub=b_ub_np,
            A_eq=A_eq_np, b_eq=b_eq_np,
            bounds=bounds_scipy, method='highs',
        )
    except Exception as e:
        return f"❌ scipy.linprog error: {e}"

    if not r.success:
        return f"❌ No óptimo: {r.message}"

    z = -r.fun if es_max else r.fun
    vars_nombres = lp.get("variables", [f"x{i+1}" for i in range(n)])
    nombres_r = lp.get("nombres_restricciones", [])

    out = ["=== SOLUCIÓN EXACTA (scipy HiGHS) ==="]
    out.append(f"Estado : {r.message}")
    out.append(f"Z {'máximo' if es_max else 'mínimo'} = {z:.6f}\n")
    out.append("Variables óptimas:")
    for nombre, val in zip(vars_nombres, r.x):
        out.append(f"  {nombre} = {val:.6f}")

    # Holguras
    if A_ub_np is not None and b_ub_np is not None and len(A_ub_np) > 0:
        out.append("\nHolguras (b - A·x):")
        for idx, (fila, rhs) in enumerate(zip(A_ub_np, b_ub_np)):
            uso = float(np.dot(fila, r.x))
            holg = float(rhs) - uso
            nombre = nombres_r[idx] if idx < len(nombres_r) else f"R{idx+1}"
            tag = " ← ACTIVA" if abs(holg) < 1e-6 else ""
            out.append(f"  {nombre}: usado={uso:.4f}, dispon={float(rhs)}, holgura={holg:.4f}{tag}")

    # Verificación
    valida, errores = verificar_solucion_lp(lp, r.x.tolist())
    if valida:
        out.append("\n✅ Verificación: solución cumple TODAS las restricciones")
    else:
        out.append(f"\n⚠️  Verificación falló: {errores}")

    return "\n".join(out)


def resolver_lp_entero(lp: dict) -> str:
    """IP con PuLP/CBC."""
    c = lp["coeficientes_c"]
    n = len(c)
    es_max = lp.get("objetivo", "maximizar").lower().startswith("max")
    sentido = pulp.LpMaximize if es_max else pulp.LpMinimize
    prob = pulp.LpProblem("IP", sentido)

    vars_nombres = lp.get("variables", [f"x{i+1}" for i in range(n)])
    bounds = lp.get("bounds") or [(0, None)] * n
    cat = 'Integer'
    x = [
        pulp.LpVariable(vars_nombres[i], lowBound=bounds[i][0], upBound=bounds[i][1], cat=cat)
        for i in range(n)
    ]

    prob += pulp.lpSum(c[i] * x[i] for i in range(n))

    for fila, rhs in zip(lp.get("A_ub") or [], lp.get("b_ub") or []):
        prob += pulp.lpSum(fila[i] * x[i] for i in range(n)) <= rhs
    for fila, rhs in zip(lp.get("A_geq") or [], lp.get("b_geq") or []):
        prob += pulp.lpSum(fila[i] * x[i] for i in range(n)) >= rhs
    for fila, rhs in zip(lp.get("A_eq") or [], lp.get("b_eq") or []):
        prob += pulp.lpSum(fila[i] * x[i] for i in range(n)) == rhs

    prob.solve(pulp.PULP_CBC_CMD(msg=False))
    estado = pulp.LpStatus[prob.status]
    if estado != 'Optimal':
        return f"❌ IP no óptimo: {estado}"

    z = pulp.value(prob.objective)
    out = ["=== SOLUCIÓN EXACTA (PuLP / CBC, enteros) ==="]
    out.append(f"Estado : {estado}")
    out.append(f"Z {'máximo' if es_max else 'mínimo'} = {z:.6f}\n")
    out.append("Variables óptimas:")
    for v in prob.variables():
        out.append(f"  {v.name} = {v.varValue}")
    return "\n".join(out)


def verificar_solucion_lp(lp: dict, x: list[float], tol: float = 1e-4) -> tuple[bool, str]:
    """Verifica que x cumple todas las restricciones del LP."""
    errores = []
    x_np = np.array(x)
    for fila, rhs in zip(lp.get("A_ub") or [], lp.get("b_ub") or []):
        if np.dot(fila, x_np) > rhs + tol:
            errores.append(f"R≤ violada: {np.dot(fila, x_np):.4f} > {rhs}")
    for fila, rhs in zip(lp.get("A_geq") or [], lp.get("b_geq") or []):
        if np.dot(fila, x_np) < rhs - tol:
            errores.append(f"R≥ violada: {np.dot(fila, x_np):.4f} < {rhs}")
    for fila, rhs in zip(lp.get("A_eq") or [], lp.get("b_eq") or []):
        if abs(np.dot(fila, x_np) - rhs) > tol:
            errores.append(f"R= violada: {np.dot(fila, x_np):.4f} ≠ {rhs}")
    bounds = lp.get("bounds") or [(0, None)] * len(x)
    for i, (lo, hi) in enumerate(bounds):
        if lo is not None and x[i] < lo - tol:
            errores.append(f"x{i+1}={x[i]:.4f} < lo={lo}")
        if hi is not None and x[i] > hi + tol:
            errores.append(f"x{i+1}={x[i]:.4f} > hi={hi}")
    return (len(errores) == 0), "; ".join(errores)


# ---------- FLUJO MÁXIMO ----------

def extraer_grafo_flujo(pregunta: str) -> Optional[dict]:
    """Extrae nodos, fuente, sumidero y arcos con capacidades."""
    llm = llm_fast(temperature=0.0)
    prompt = f"""Extrae la red de flujo máximo del siguiente problema. Devuelve SOLO JSON:

{{
  "fuente": "1",
  "sumidero": "4",
  "arcos": [
    {{"de": "1", "a": "2", "capacidad": 50}},
    {{"de": "1", "a": "3", "capacidad": 30}},
    {{"de": "2", "a": "4", "capacidad": 40}},
    {{"de": "3", "a": "4", "capacidad": 40}}
  ]
}}

⚠️ REGLAS CRÍTICAS:
1. USA SOLO los nodos que aparecen en el enunciado. NO inventes nodos S, T, A, B
   si no están explícitamente mencionados.

2. Si el enunciado NO menciona explícitamente cuál es la fuente y cuál el sumidero,
   DEDÚCELO de la estructura del grafo:
   - FUENTE = el nodo que solo TIENE arcos SALIENTES (nadie le envía flujo)
   - SUMIDERO = el nodo que solo TIENE arcos ENTRANTES (no envía a nadie)

3. Ejemplo: "Nodo 1 a 2, 1 a 3, 2 a 4, 3 a 4"
   → El nodo 1 solo tiene arcos saliendo → fuente = "1"
   → El nodo 4 solo tiene arcos entrando → sumidero = "4"
   → Los nodos 2 y 3 son intermedios.

4. Los nombres de nodos deben coincidir EXACTAMENTE con los del enunciado.
   Si dice "Nodo 1", usa "1". Si dice "Nodo S", usa "S". Si dice "A", usa "A".

5. Las capacidades deben ser números (no strings con unidades).
   "50 Mbps" → 50

Si no es problema de flujo: {{"es_flujo": false}}

PROBLEMA:
{pregunta}
"""
    try:
        raw = con_retry(_invoke, llm, prompt, etiqueta="parse-flujo")
        raw = re.sub(r"```json|```", "", raw).strip()
        d = json.loads(raw)
        if d.get("es_flujo") is False:
            return None
        return d
    except Exception:
        return None


def resolver_flujo_max(grafo_data: dict) -> str:

    # 🔍 DEBUG
    print(f"   📋 Grafo extraído:")
    print(f"      Fuente   : {grafo_data.get('fuente')}")
    print(f"      Sumidero : {grafo_data.get('sumidero')}")
    print(f"      Arcos    : {len(grafo_data.get('arcos', []))} arcos")
    for a in grafo_data.get('arcos', []):
        print(f"        {a['de']} → {a['a']} (cap={a['capacidad']})")



    G = nx.DiGraph()
    for arco in grafo_data["arcos"]:
        G.add_edge(arco["de"], arco["a"], capacity=float(arco["capacidad"]))
    fuente = grafo_data["fuente"]
    sumidero = grafo_data["sumidero"]
    flow_value, flow_dict = nx.maximum_flow(G, fuente, sumidero)

    out = ["=== SOLUCIÓN EXACTA (Ford-Fulkerson / Edmonds-Karp) ==="]
    out.append(f"Flujo máximo: {fuente} → {sumidero} = {flow_value}\n")
    out.append("Asignación de flujo por arco:")
    for u, vecinos in flow_dict.items():
        for v, f in vecinos.items():
            cap = G[u][v]["capacity"]
            tag = " ← SATURADO" if abs(f - cap) < 1e-6 and f > 0 else ""
            if f > 0:
                out.append(f"  {u} → {v}: flujo={f:.2f} / capacidad={cap:.2f}{tag}")

    # Corte mínimo
    cut_value, (S_set, T_set) = nx.minimum_cut(G, fuente, sumidero)
    out.append(f"\nCorte mínimo = {cut_value} (= flujo máximo, teorema max-flow min-cut)")
    out.append(f"Conjunto S: {sorted(S_set)}")
    out.append(f"Conjunto T: {sorted(T_set)}")
    return "\n".join(out)


# ---------- RUTA MÁS CORTA ----------

def extraer_grafo_ruta(pregunta: str) -> Optional[dict]:
    llm = llm_fast(temperature=0.0)
    prompt = f"""Extrae el grafo de ruta más corta. Devuelve SOLO JSON:

{{
  "inicio": "A",
  "fin": "E",
  "dirigido": false,
  "aristas": [
    {{"de": "A", "a": "B", "peso": 4}}
  ]
}}

Si no es ruta más corta: {{"es_ruta": false}}

PROBLEMA:
{pregunta}
"""
    try:
        raw = con_retry(_invoke, llm, prompt, etiqueta="parse-ruta")
        raw = re.sub(r"```json|```", "", raw).strip()
        d = json.loads(raw)
        if d.get("es_ruta") is False:
            return None
        return d
    except Exception:
        return None


def resolver_ruta_corta(data: dict) -> str:
    G = nx.DiGraph() if data.get("dirigido") else nx.Graph()
    for arista in data["aristas"]:
        G.add_edge(arista["de"], arista["a"], weight=float(arista["peso"]))
    try:
        ruta = nx.shortest_path(G, data["inicio"], data["fin"], weight="weight")
        dist = nx.shortest_path_length(G, data["inicio"], data["fin"], weight="weight")
    except nx.NetworkXNoPath:
        return f"❌ No existe ruta entre {data['inicio']} y {data['fin']}"

    out = ["=== SOLUCIÓN EXACTA (Dijkstra, networkx) ==="]
    out.append(f"Ruta: {' → '.join(ruta)}")
    out.append(f"Distancia total: {dist}")
    return "\n".join(out)


# ---------- PERT / CPM ----------

def extraer_pert(pregunta: str) -> Optional[dict]:
    llm = llm_fast(temperature=0.0)
    prompt = f"""Extrae la tabla de actividades del proyecto PERT/CPM. Devuelve SOLO JSON:

{{
  "actividades": [
    {{"nombre": "A", "duracion": 3, "predecesores": []}},
    {{"nombre": "B", "duracion": 5, "predecesores": ["A"]}}
  ]
}}

Si no es PERT/CPM: {{"es_pert": false}}

PROBLEMA:
{pregunta}
"""
    try:
        raw = con_retry(_invoke, llm, prompt, etiqueta="parse-pert")
        raw = re.sub(r"```json|```", "", raw).strip()
        d = json.loads(raw)
        if d.get("es_pert") is False:
            return None
        return d
    except Exception:
        return None


def resolver_pert(data: dict) -> str:
    """Calcula early/late times, holguras y ruta crítica."""
    acts = {a["nombre"]: a for a in data["actividades"]}
    nombres = list(acts.keys())

    # Forward pass: ES (Early Start), EF (Early Finish)
    ES, EF = {}, {}
    pendientes = set(nombres)
    while pendientes:
        progreso = False
        for n in list(pendientes):
            preds = acts[n]["predecesores"]
            if all(p in EF for p in preds):
                ES[n] = max([EF[p] for p in preds], default=0)
                EF[n] = ES[n] + acts[n]["duracion"]
                pendientes.remove(n)
                progreso = True
        if not progreso:
            return "❌ Ciclo o predecesores inválidos en el grafo"

    duracion_proyecto = max(EF.values())

    # Backward pass: LF (Late Finish), LS (Late Start)
    sucesores = {n: [] for n in nombres}
    for n in nombres:
        for p in acts[n]["predecesores"]:
            sucesores[p].append(n)

    LF, LS = {}, {}
    pendientes = set(nombres)
    while pendientes:
        progreso = False
        for n in list(pendientes):
            sucs = sucesores[n]
            if all(s in LS for s in sucs):
                LF[n] = min([LS[s] for s in sucs], default=duracion_proyecto)
                LS[n] = LF[n] - acts[n]["duracion"]
                pendientes.remove(n)
                progreso = True
        if not progreso:
            return "❌ Error en backward pass"

    # Holguras
    holguras = {n: LS[n] - ES[n] for n in nombres}
    criticas = [n for n, h in holguras.items() if abs(h) < 1e-9]

    out = ["=== SOLUCIÓN EXACTA (PERT/CPM) ==="]
    out.append(f"Duración del proyecto: {duracion_proyecto}\n")
    out.append(f"{'Act':<6} {'Dur':<5} {'ES':<5} {'EF':<5} {'LS':<5} {'LF':<5} {'Holg':<6} {'Crit'}")
    for n in nombres:
        crit = "✓" if n in criticas else ""
        out.append(f"{n:<6} {acts[n]['duracion']:<5} {ES[n]:<5} {EF[n]:<5} {LS[n]:<5} {LF[n]:<5} {holguras[n]:<6} {crit}")
    out.append(f"\nRuta crítica: {' → '.join(criticas)}")
    return "\n".join(out)


# ---------- COLAS M/M/1 ----------

def extraer_colas(pregunta: str) -> Optional[dict]:
    """Extrae parámetros de cola. Primero intenta regex, luego LLM."""

    # ============ CAPA 1: Regex (rápido, 0 tokens) ============
    pregunta_norm = pregunta.lower().replace(',', '.')

    # Buscar lambda: "lambda = 3", "λ = 3", "tasa de llegada = 3", "λ=3"
    lambda_match = re.search(
        r'(?:lambda|λ|tasa de llegada)\s*[=:]?\s*(\d+(?:\.\d+)?)',
        pregunta_norm
    )

    # Buscar mu: "mu = 5", "μ = 5", "tasa de servicio = 5"
    mu_match = re.search(
        r'(?:\bmu\b|μ|tasa de servicio)\s*[=:]?\s*(\d+(?:\.\d+)?)',
        pregunta_norm
    )

    # Buscar c (servidores): "c = 2", "2 servidores", "c=3"
    c_match = re.search(
        r'(?:\bc\s*[=:]?\s*(\d+)|(\d+)\s*servidores?)',
        pregunta_norm
    )
    c = 1  # default M/M/1
    if c_match:
        c = int(c_match.group(1) or c_match.group(2))

    if lambda_match and mu_match:
        return {
            "tipo": "M/M/1" if c == 1 else f"M/M/{c}",
            "lambda": float(lambda_match.group(1)),
            "mu": float(mu_match.group(1)),
            "c": c,
        }

    # ============ CAPA 2: LLM como fallback ============
    llm = llm_fast(temperature=0.0)
    prompt = f"""Extrae los parámetros del sistema de colas. Devuelve SOLO JSON:

{{
  "tipo": "M/M/1" | "M/M/c",
  "lambda": 10,
  "mu": 12,
  "c": 1
}}

REGLAS:
- "lambda" = tasa de llegada (clientes por unidad de tiempo)
- "mu" = tasa de servicio (clientes por unidad de tiempo)
- "c" = número de servidores (default 1 para M/M/1)

EJEMPLOS:
- "λ=3 autos/h, μ=5 autos/h" → {{"tipo":"M/M/1","lambda":3,"mu":5,"c":1}}
- "tasa de llegada 10, tasa de servicio 12" → {{"tipo":"M/M/1","lambda":10,"mu":12,"c":1}}

Si no es problema de colas: {{"es_colas": false}}

PROBLEMA:
{pregunta}
"""
    try:
        raw = con_retry(_invoke, llm, prompt, etiqueta="parse-colas")
        raw = re.sub(r"```json|```", "", raw).strip()
        d = json.loads(raw)
        if d.get("es_colas") is False:
            return None
        return d
    except Exception as e:
        print(f"⚠️  Parser colas falló: {e}")
        return None


def resolver_colas(data: dict) -> str:

    # 🔍 DEBUG
    print(f"   📋 Parámetros extraídos:")
    print(f"      λ (lambda) = {data.get('lambda')}")
    print(f"      μ (mu)     = {data.get('mu')}")
    print(f"      c          = {data.get('c', 1)}")

    lam = float(data["lambda"])

    mu = float(data["mu"])
    c = int(data.get("c", 1))
    rho = lam / (c * mu)

    if rho >= 1:
        return f"❌ Sistema inestable (ρ = {rho:.4f} ≥ 1). Las colas crecen sin límite."

    out = ["=== SOLUCIÓN EXACTA (Teoría de Colas) ==="]
    out.append(f"λ = {lam}, μ = {mu}, c = {c}")

    if c == 1:
        L = lam / (mu - lam)
        Lq = (lam ** 2) / (mu * (mu - lam))
        W = 1 / (mu - lam)
        Wq = lam / (mu * (mu - lam))
        P0 = 1 - rho
        out.append(f"\n--- M/M/1 ---")
    else:
        # M/M/c
        suma = sum((lam/mu)**n / math.factorial(n) for n in range(c))
        suma += ((lam/mu)**c / math.factorial(c)) * (1 / (1 - rho))
        P0 = 1 / suma
        Lq = (P0 * (lam/mu)**c * rho) / (math.factorial(c) * (1 - rho)**2)
        L = Lq + lam/mu
        Wq = Lq / lam
        W = Wq + 1/mu
        out.append(f"\n--- M/M/{c} ---")

    out.append(f"ρ (utilización)         = {rho:.4f} ({rho*100:.2f}%)")
    out.append(f"P0 (sistema vacío)      = {P0:.4f}")
    out.append(f"L  (clientes en sistema)= {L:.4f}")
    out.append(f"Lq (clientes en cola)   = {Lq:.4f}")
    out.append(f"W  (tiempo en sistema)  = {W:.4f}")
    out.append(f"Wq (tiempo en cola)     = {Wq:.4f}")
    return "\n".join(out)


# ---------- EOQ ----------

def extraer_eoq(pregunta: str) -> Optional[dict]:
    llm = llm_fast(temperature=0.0)
    prompt = f"""Extrae los parámetros de inventario EOQ. Devuelve SOLO JSON:

{{
  "demanda_anual": 10000,
  "costo_pedido": 50,
  "costo_mantenimiento": 2,
  "demanda_diaria": null,
  "lead_time": null
}}

Pon null en lo que no aparezca. Si no es EOQ/inventario: {{"es_eoq": false}}

PROBLEMA:
{pregunta}
"""
    try:
        raw = con_retry(_invoke, llm, prompt, etiqueta="parse-eoq")
        raw = re.sub(r"```json|```", "", raw).strip()
        d = json.loads(raw)
        if d.get("es_eoq") is False:
            return None
        return d
    except Exception:
        return None


def resolver_eoq(data: dict) -> str:
    out = ["=== SOLUCIÓN EXACTA (Modelo EOQ / Wilson) ==="]

    D = data.get("demanda_anual")
    S = data.get("costo_pedido")
    H = data.get("costo_mantenimiento")
    if D and S and H:
        Q = math.sqrt(2 * D * S / H)
        N = D / Q
        T = Q / D
        CT = math.sqrt(2 * D * S * H)
        out.append(f"D = {D}, S = {S}, H = {H}")
        out.append(f"Q* (cantidad óptima)     = {Q:.4f} unidades")
        out.append(f"N  (pedidos por año)     = {N:.4f}")
        out.append(f"T  (ciclo en años)       = {T:.4f}")
        out.append(f"CT (costo total óptimo)  = {CT:.4f}")

    d = data.get("demanda_diaria")
    L = data.get("lead_time")
    if d and L:
        ROP = d * L
        out.append(f"\nROP (punto de reorden) = {d} × {L} = {ROP} unidades")

    if len(out) == 1:
        return "❌ Faltan parámetros para resolver EOQ"
    return "\n".join(out)


# ---------- TRANSPORTE ----------

def extraer_transporte(pregunta: str) -> Optional[dict]:
    """Extrae oferta, demanda y matriz de costos."""
    llm = llm_fast(temperature=0.0)
    prompt = f"""Extrae el problema de transporte. Devuelve SOLO JSON:

{{
  "origenes": ["P1", "P2"],
  "destinos": ["C1", "C2"],
  "oferta": [100, 200],
  "demanda": [150, 150],
  "costos": [[2, 4], [3, 2]]
}}

⚠️ REGLA CRÍTICA: Este extractor es SOLO para transporte de 2 capas.
Si el problema tiene NODOS INTERMEDIOS (ej: "A pasa por B antes de llegar a C",
"puede ir directo o vía punto intermedio"), devuelve {{"es_transporte": false}}.

Para nodos intermedios, se necesita un modelo de balance de flujo en red, NO
el modelo clásico de transporte.

costos[i][j] = costo de enviar de origen i a destino j.
Si la oferta total != demanda total, agrega un origen o destino ficticio con costo 0.

Si no es transporte O tiene nodos intermedios: {{"es_transporte": false}}

PROBLEMA:
{pregunta}
"""
    try:
        raw = con_retry(_invoke, llm, prompt, etiqueta="parse-transp")
        raw = re.sub(r"```json|```", "", raw).strip()
        d = json.loads(raw)
        if d.get("es_transporte") is False:
            return None
        return d
    except Exception:
        return None


def resolver_transporte(data: dict) -> str:
    """Formula como LP y resuelve con scipy. m·n variables."""
    origenes = data["origenes"]
    destinos = data["destinos"]
    oferta = data["oferta"]
    demanda = data["demanda"]
    costos = data["costos"]
    m, n = len(origenes), len(destinos)

    if sum(oferta) != sum(demanda):
        return f"❌ Problema desbalanceado: oferta={sum(oferta)} ≠ demanda={sum(demanda)}. Balancea con origen/destino ficticio."

    # Variables x[i][j]: cantidad enviada de origen i a destino j (m·n vars)
    c = []
    for i in range(m):
        for j in range(n):
            c.append(costos[i][j])

    # Restricciones de oferta: sum_j x[i][j] = oferta[i]  para cada i
    A_eq = []
    b_eq = []
    for i in range(m):
        fila = [0.0] * (m * n)
        for j in range(n):
            fila[i * n + j] = 1.0
        A_eq.append(fila)
        b_eq.append(oferta[i])
    # Restricciones de demanda: sum_i x[i][j] = demanda[j]  para cada j
    for j in range(n):
        fila = [0.0] * (m * n)
        for i in range(m):
            fila[i * n + j] = 1.0
        A_eq.append(fila)
        b_eq.append(demanda[j])

    bounds = [(0, None)] * (m * n)
    r = linprog(c=c, A_eq=A_eq, b_eq=b_eq, bounds=bounds, method='highs')

    if not r.success:
        return f"❌ scipy.linprog no resolvió transporte: {r.message}"

    out = ["=== SOLUCIÓN EXACTA (Transporte como LP, scipy HiGHS) ==="]
    out.append(f"Costo total mínimo: {r.fun:.4f}\n")
    out.append("Asignaciones óptimas (no cero):")
    for i in range(m):
        for j in range(n):
            x = r.x[i * n + j]
            if x > 1e-6:
                out.append(f"  {origenes[i]} → {destinos[j]}: {x:.2f} unidades × ${costos[i][j]} = ${x * costos[i][j]:.2f}")
    return "\n".join(out)


# ---------- RED DE TRANSPORTE (con nodos intermedios) ----------

def extraer_red_transporte(pregunta: str) -> Optional[dict]:
    """Extrae red de transporte con posibles nodos intermedios."""
    llm = llm_fast(temperature=0.0)
    prompt = f"""Extrae el problema de transporte como red de flujo. Devuelve SOLO JSON:

{{
  "nodos": [
    {{"nombre": "A", "balance": 10}},
    {{"nombre": "B", "balance": 0}},
    {{"nombre": "C", "balance": -10}}
  ],
  "arcos": [
    {{"de": "A", "a": "B", "costo": 5, "capacidad": null}},
    {{"de": "B", "a": "C", "costo": 3, "capacidad": null}},
    {{"de": "A", "a": "C", "costo": 10, "capacidad": null}}
  ]
}}

REGLAS DE BALANCE:
- balance > 0 : nodo OFERTA (genera esa cantidad).
- balance < 0 : nodo DEMANDA (consume |balance|).
- balance = 0 : nodo INTERMEDIO (conserva flujo).
- SUMA de todos los balance DEBE ser 0.
- capacidad: null = sin límite. Solo pon número si hay tope explícito.

Si no es red de transporte: {{"es_red": false}}

PROBLEMA:
{pregunta}
"""
    try:
        raw = con_retry(_invoke, llm, prompt, etiqueta="parse-red-transp")
        raw = re.sub(r"```json|```", "", raw).strip()
        d = json.loads(raw)
        if d.get("es_red") is False:
            return None
        return d
    except Exception as e:
        print(f"⚠️  Parser red-transporte falló: {e}")
        return None


def resolver_red_transporte(data: dict) -> str:
    """Red de transporte con nodos intermedios. LP con balance de flujo."""
    nodos = data["nodos"]
    arcos = data["arcos"]
    nombres = [n["nombre"] for n in nodos]
    balance = {n["nombre"]: float(n["balance"]) for n in nodos}

    if abs(sum(balance.values())) > 1e-6:
        return (f"❌ Red desbalanceada: Σ balance = {sum(balance.values()):.4f} ≠ 0. "
                f"Agrega un nodo ficticio.")

    n_vars = len(arcos)
    c = [float(a["costo"]) for a in arcos]

    # Una restricción de balance por cada nodo
    A_eq, b_eq = [], []
    for k in nombres:
        fila = [0.0] * n_vars
        for idx, a in enumerate(arcos):
            if a["de"] == k:
                fila[idx] += 1.0   # sale
            if a["a"] == k:
                fila[idx] -= 1.0   # entra
        A_eq.append(fila)
        b_eq.append(balance[k])

    bounds = []
    for a in arcos:
        cap = a.get("capacidad")
        bounds.append((0, cap if cap is not None else None))

    r = linprog(c=c, A_eq=A_eq, b_eq=b_eq, bounds=bounds, method='highs')
    if not r.success:
        return f"❌ scipy.linprog no resolvió red de transporte: {r.message}"

    out = ["=== SOLUCIÓN EXACTA (Red de Transporte con intermedios, scipy HiGHS) ==="]
    out.append(f"Costo total mínimo: {r.fun:.4f}\n")
    out.append("Flujo óptimo por arco (no cero):")
    for idx, a in enumerate(arcos):
        x = r.x[idx]
        if x > 1e-6:
            out.append(f"  {a['de']} → {a['a']}: {x:.2f} u × ${a['costo']} = ${x * a['costo']:.2f}")

    # Verificación de balance
    out.append("\nVerificación de balance por nodo:")
    for k in nombres:
        sale = sum(r.x[i] for i, a in enumerate(arcos) if a["de"] == k)
        entra = sum(r.x[i] for i, a in enumerate(arcos) if a["a"] == k)
        neto = sale - entra
        out.append(f"  {k}: sale={sale:.2f}, entra={entra:.2f}, neto={neto:+.2f} (esperado {balance[k]:+.2f})")

    return "\n".join(out)


# ---------- ASIGNACIÓN (algoritmo Húngaro) ----------

def extraer_asignacion(pregunta: str) -> Optional[dict]:
    llm = llm_fast(temperature=0.0)
    prompt = f"""Extrae el problema de asignación. Devuelve SOLO JSON:

{{
  "agentes": ["A", "B", "C"],
  "tareas": ["T1", "T2", "T3"],
  "costos": [[10, 5, 8], [6, 9, 4], [7, 3, 11]],
  "objetivo": "minimizar"
}}

costos[i][j] = costo de asignar agente i a tarea j. Matriz CUADRADA.
Si es maximizar (ganancia), pon "objetivo": "maximizar".

Si no es asignación: {{"es_asignacion": false}}

PROBLEMA:
{pregunta}
"""
    try:
        raw = con_retry(_invoke, llm, prompt, etiqueta="parse-asig")
        raw = re.sub(r"```json|```", "", raw).strip()
        d = json.loads(raw)
        if d.get("es_asignacion") is False:
            return None
        return d
    except Exception:
        return None


def resolver_asignacion(data: dict) -> str:
    """scipy.optimize.linear_sum_assignment (algoritmo Húngaro)."""
    agentes = data["agentes"]
    tareas = data["tareas"]
    matriz = np.array(data["costos"], dtype=float)
    es_max = data.get("objetivo", "minimizar").lower().startswith("max")

    if matriz.shape[0] != matriz.shape[1]:
        return f"❌ Matriz no cuadrada: {matriz.shape}. Balancea agregando filas/columnas ficticias."

    # Hungaro minimiza por defecto. Para max negamos.
    matriz_solver = -matriz if es_max else matriz
    fila_idx, col_idx = linear_sum_assignment(matriz_solver)

    out = ["=== SOLUCIÓN EXACTA (Algoritmo Húngaro, scipy) ==="]
    sentido = "máximo" if es_max else "mínimo"
    valor_total = float(matriz[fila_idx, col_idx].sum())
    out.append(f"Valor {sentido} total: {valor_total:.4f}\n")
    out.append("Asignación óptima:")
    for i, j in zip(fila_idx, col_idx):
        out.append(f"  {agentes[i]} ↔ {tareas[j]}: costo = {matriz[i][j]:.2f}")
    return "\n".join(out)


# ---------- NLP (Programación No Lineal) ----------

def extraer_nlp(pregunta: str) -> Optional[dict]:
    """Extrae función objetivo, variables y restricciones simbólicas como expresiones Python."""
    llm = ChatGroq(
        model=MODEL_REASONING,
        temperature=0.0,
        api_key=GROQ_API_KEY,
        reasoning_effort="medium",  # razonamiento medio para sustituir álgebra
        max_tokens=2048,
    )
    prompt = f"""Extrae el problema de optimización no lineal. Devuelve SOLO JSON con expresiones Python válidas:

{{
  "variables": ["x", "y"],
  "objetivo": "minimizar" | "maximizar",
  "funcion_objetivo": "150*x + 100000/x",
  "restricciones_eq": ["x*y - 1000"],
  "restricciones_ineq": [],
  "x0": [10, 100],
  "bounds": [[0.01, null], [0.01, null]]
}}

REGLAS DE EXPRESIONES:
- funcion_objetivo: expresión Python como string usando los nombres de variables.
- Operadores válidos: + - * / ** ( )
- Funciones disponibles: sqrt, log, exp, sin, cos, tan, pi, e (de la librería math)
- restricciones_eq: cada string es la EXPR del lado izquierdo, asumiendo "= 0".
  Ejemplo: "x*y - 1000" significa x*y = 1000.
- restricciones_ineq: cada string es EXPR >= 0.
  Ejemplo para x+y <= 10: pasa "10 - x - y" (que es >= 0).
- x0: punto inicial razonable (positivo si las variables son físicas, dentro de bounds).
- bounds: [[lo, hi], ...] mismo orden que variables. Usa null para infinito.

OPTIMIZACIÓN: Si una variable se puede despejar con una restricción de igualdad,
SIEMPRE sustitúyela y elimínala del problema. Esto reduce dimensiones y evita
problemas numéricos en el solver.

EJEMPLO 1: "minimizar 150x + 100y, sujeto a xy = 1000"
→ despeja y = 1000/x y sustituye:
{{"variables": ["x"], "objetivo": "minimizar",
  "funcion_objetivo": "150*x + 100*(1000/x)",
  "restricciones_eq": [], "restricciones_ineq": [],
  "x0": [10], "bounds": [[0.01, null]]}}

EJEMPLO 2: "P = 100 - 0.01Q, C = 50Q + 10000, maximizar Z = P*Q - C"
→ P está definido como función de Q, así que sustituye P en Z:
   Z = (100 - 0.01Q)*Q - (50Q + 10000)
   Z = 100Q - 0.01Q² - 50Q - 10000
   Z = -0.01Q² + 50Q - 10000
{{"variables": ["Q"], "objetivo": "maximizar",
  "funcion_objetivo": "-0.01*Q**2 + 50*Q - 10000",
  "restricciones_eq": [], "restricciones_ineq": [],
  "x0": [1000], "bounds": [[0.01, null]]}}

⚠️ REGLA CRÍTICA: Si el enunciado dice "P = f(Q)" o "y = g(x)", NUNCA trates
esa variable como independiente. Siempre sustituye y deja solo la variable base.
Esto aplica también a fórmulas de demanda, precio, costo unitario, etc.

Si no es NLP: {{"es_nlp": false}}

PROBLEMA:
{pregunta}
"""
    try:
        raw = con_retry(_invoke, llm, prompt, etiqueta="parse-nlp")
        raw = re.sub(r"```json|```", "", raw).strip()
        d = json.loads(raw)
        if d.get("es_nlp") is False:
            return None
        return d
    except Exception as e:
        print(f"⚠️  Parser NLP falló: {e}")
        return None


def validar_expresion_nlp(expr: str, variables: list) -> tuple[bool, str]:
    """
    Verifica que una expresión Python solo use las variables declaradas
    y funciones matemáticas conocidas. Retorna (es_valida, mensaje_error).
    """
    funciones_permitidas = {
        'sqrt', 'log', 'exp', 'sin', 'cos', 'tan',
        'pi', 'e', 'ln', 'abs', 'arcsin', 'arccos', 'arctan'
    }
    permitidas = set(variables) | funciones_permitidas

    # Extraer todos los identificadores (palabras alfabéticas) de la expresión
    identificadores = set(re.findall(r'\b[a-zA-Z_][a-zA-Z0-9_]*\b', expr))

    # Buscar identificadores que NO sean variables ni funciones permitidas
    no_definidos = identificadores - permitidas

    if no_definidos:
        return False, (
            f"La expresión '{expr}' usa variables no definidas: {no_definidos}. "
            f"Variables declaradas: {variables}. "
            f"Probablemente el extractor olvidó sustituir fórmulas (P, C, etc.)."
        )
    return True, ""

def resolver_nlp(data: dict) -> str:
    """scipy.optimize.minimize con SLSQP."""
    variables = data["variables"]
    n = len(variables)
    es_max = data.get("objetivo", "minimizar").lower().startswith("max")

    # 🔍 DEBUG: mostrar el JSON extraído para diagnosticar problemas de formulación
    print(f"   📋 JSON extraído por el LLM:")
    print(f"      Variables       : {data.get('variables')}")
    print(f"      Función objetivo: {data.get('funcion_objetivo')}")
    print(f"      Restricciones eq: {data.get('restricciones_eq')}")
    print(f"      Restricciones ineq: {data.get('restricciones_ineq')}")
    print(f"      Punto inicial   : {data.get('x0')}")
    print(f"      Bounds          : {data.get('bounds')}")


    # 🔍 VALIDAR que las expresiones solo usen variables declaradas
    fo = data.get("funcion_objetivo", "")
    valida, error = validar_expresion_nlp(fo, variables)
    if not valida:
        return (f"❌ Formulación NLP inválida: {error}\n\n"
                f"👉 El extractor no expandió correctamente las fórmulas. "
                f"La explicación del LLM abajo (que usa derivadas) es la correcta.")

    for expr in (data.get("restricciones_eq") or []) + (data.get("restricciones_ineq") or []):
        valida, error = validar_expresion_nlp(expr, variables)
        if not valida:
            return f"❌ Restricción inválida: {error}"

    # Contexto seguro para eval: solo math y las variables
    def make_eval_func(expr: str, sign: float = 1.0):
        # Compilar una vez para acelerar
        codigo = compile(expr, "<nlp_expr>", "eval")
        def f(x):
            ctx = {v: float(x[i]) for i, v in enumerate(variables)}
            ctx.update({
                "sqrt": math.sqrt, "log": math.log, "exp": math.exp,
                "sin": math.sin, "cos": math.cos, "tan": math.tan,
                "pi": math.pi, "e": math.e, "ln": math.log,
                "abs": abs,
            })
            return sign * eval(codigo, {"__builtins__": {}}, ctx)
        return f

    try:
        obj_func = make_eval_func(data["funcion_objetivo"], sign=-1.0 if es_max else 1.0)
    except Exception as e:
        return f"❌ No pude compilar la función objetivo: {e}"

    constraints = []
    try:
        for expr in data.get("restricciones_eq") or []:
            constraints.append({"type": "eq", "fun": make_eval_func(expr)})
        for expr in data.get("restricciones_ineq") or []:
            constraints.append({"type": "ineq", "fun": make_eval_func(expr)})
    except Exception as e:
        return f"❌ Error compilando restricciones: {e}"

    bounds = data.get("bounds") or [(None, None)] * n
    bounds = [tuple(b) if b else (None, None) for b in bounds]
    x0 = data.get("x0") or [1.0] * n

    try:
        r = minimize(
            obj_func, x0, method="SLSQP",
            bounds=bounds, constraints=constraints,
            options={"ftol": 1e-12, "maxiter": 500},
        )
    except Exception as e:
        return f"❌ scipy.optimize falló: {e}"

    if not r.success:
        # Intentar con un punto inicial diferente
        try:
            x0_alt = [v * 2 + 1 for v in x0]
            r = minimize(obj_func, x0_alt, method="SLSQP",
                         bounds=bounds, constraints=constraints,
                         options={"ftol": 1e-9, "maxiter": 1000})
        except Exception:
            pass

    if not r.success:
        return f"❌ NLP no convergió: {r.message}"

    valor = -r.fun if es_max else r.fun

    out = ["=== SOLUCIÓN EXACTA (NLP, scipy.optimize SLSQP) ==="]
    out.append(f"Estado : {r.message}")
    out.append(f"Iteraciones: {r.nit}")
    out.append(f"Valor {'máximo' if es_max else 'mínimo'} de la función objetivo = {valor:.6f}\n")
    out.append("Variables óptimas:")
    for nombre, val in zip(variables, r.x):
        out.append(f"  {nombre} = {val:.6f}")

    # Verificar restricciones
    if constraints:
        out.append("\nVerificación de restricciones:")
        for i, expr in enumerate(data.get("restricciones_eq") or []):
            f = make_eval_func(expr)
            val_eq = f(r.x)
            out.append(f"  EQ '{expr} = 0' → evaluado = {val_eq:.6e}")
        for i, expr in enumerate(data.get("restricciones_ineq") or []):
            f = make_eval_func(expr)
            val_ineq = f(r.x)
            tag = " ✓" if val_ineq >= -1e-6 else " ✗"
            out.append(f"  INEQ '{expr} >= 0' → evaluado = {val_ineq:.6e}{tag}")

    # 🚨 SANITY CHECK: detectar resultados absurdos
    if abs(valor) > 1e9:
        out.append(f"\n⚠️⚠️⚠️ ADVERTENCIA CRÍTICA ⚠️⚠️⚠️")
        out.append(f"El solver convergió a un valor absurdamente grande: {valor:.2e}")
        out.append(f"Esto casi siempre indica que el problema fue MAL FORMULADO por el extractor.")
        out.append(f"Posibles causas:")
        out.append(f"  - Variables que debieron sustituirse pero quedaron separadas")
        out.append(f"    (ej: P y Q como independientes cuando P = f(Q))")
        out.append(f"  - Restricciones no lineales mal expresadas")
        out.append(f"  - Punto inicial (x0) muy lejos del óptimo")
        out.append(f"\n👉 RECOMENDACIÓN: Ignora estos números. La explicación del LLM")
        out.append(f"   abajo (que usa derivadas) es probablemente la respuesta correcta.")

    # 🚨 SANITY CHECK 2: variable principal cerca de 0 cuando debería ser positiva
    for nombre, val in zip(variables, r.x):
        if 0 < val < 0.1 and abs(valor) > 1e6:
            out.append(f"\n⚠️  La variable {nombre}={val:.4f} es sospechosamente pequeña.")
            out.append(f"   Combinado con un valor objetivo enorme, sugiere mala formulación.")
            break

    return "\n".join(out)


# =============================================================
# ROUTER PRINCIPAL
# =============================================================

def resolver_numericamente(pregunta: str, tipo: str) -> tuple[str, str]:
    """
    Devuelve (solucion_exacta, tipo_efectivo). Si no se pudo, ('', tipo).
    """
    try:
        if tipo in ("LP", "IP"):
            lp = extraer_lp_json(pregunta)
            if not lp or not lp.get("es_lp"):
                return "", tipo
            if tipo == "IP" or lp.get("enteras"):
                return resolver_lp_entero(lp), "IP"
            return resolver_lp_continuo(lp), "LP"

        if tipo == "TRANSPORTE":
            # Intentar modelo clásico de 2 capas
            data = extraer_transporte(pregunta)
            if data:
                return resolver_transporte(data), tipo

            # Fallback: modelo de red con nodos intermedios
            print("   ⚠️  Transporte clásico rechazado, probando modelo de red...")
            data_red = extraer_red_transporte(pregunta)
            if data_red:
                return resolver_red_transporte(data_red), tipo

        if tipo == "ASIGNACION":
            data = extraer_asignacion(pregunta)
            if data:
                return resolver_asignacion(data), tipo

        if tipo == "FLUJO_MAX":
            data = extraer_grafo_flujo(pregunta)
            if data:
                return resolver_flujo_max(data), tipo

        if tipo == "RUTA_CORTA":
            data = extraer_grafo_ruta(pregunta)
            if data:
                return resolver_ruta_corta(data), tipo

        if tipo == "PERT_CPM":
            data = extraer_pert(pregunta)
            if data:
                return resolver_pert(data), tipo

        if tipo in ("COLAS_MM1", "COLAS_MMC"):
            data = extraer_colas(pregunta)
            if data:
                return resolver_colas(data), tipo

        if tipo == "EOQ":
            data = extraer_eoq(pregunta)
            if data:
                return resolver_eoq(data), tipo

        if tipo == "NLP":
            data = extraer_nlp(pregunta)
            if data:
                return resolver_nlp(data), tipo
    except Exception as e:
        print(f"⚠️  Solver numérico falló para {tipo}: {e}")

    return "", tipo


# =============================================================
# CONSTRUCCIÓN DEL PROMPT FINAL
# =============================================================

def construir_prompt(pregunta: str, tipo: str, solucion_exacta: str, teoria: str) -> str:
    """
    Prompt enriquecido con:
      - Tipo detectado
      - Solución numérica exacta (si la hay) → el LLM solo explica
      - Teoría del libro Hillier (RAG)
    """
    teoria_block = ""
    if teoria:
        teoria_block = f"\n\n=== CONTEXTO DEL LIBRO HILLIER (referencia teórica) ===\n{teoria}"

    solucion_block = ""
    if solucion_exacta:
        solucion_block = f"""

=== SOLUCIÓN NUMÉRICA EXACTA (calculada por solver determinístico) ===
{solucion_exacta}

CRÍTICO: Los números de arriba son la verdad. NO los recalcules. NO los modifiques.
Tu trabajo es EXPLICAR la formulación matemática y por qué esta es la solución óptima.
"""

    return f"""Eres un profesor universitario experto en Investigación de Operaciones,
con formación rigurosa en Hillier-Lieberman, Taha y Winston. El problema fue
clasificado como tipo: {tipo}.
{teoria_block}
{solucion_block}

=== PROBLEMA A RESOLVER ===
{pregunta}

⚠️ FORMATO OBLIGATORIO DE TU RESPUESTA ⚠️

Tu respuesta se va a leer en una TERMINAL DE TEXTO (Google Colab, consola).
NO puede contener:
  ❌ LaTeX: nada de \\[, \\], \\(, \\), \\frac, \\sum, \\max, \\min, \\sqrt, \\cdot, \\le, \\ge, \\neq, \\infty
  ❌ Bloques matemáticos $$...$$ ni inline $...$
  ❌ \\\\ ni \\begin{{align}} ni \\begin{{cases}}
  ❌ Tablas markdown con | --- | (no se renderiza en terminal)

SÍ puedes y DEBES usar:
  ✅ Texto plano normal con saltos de línea
  ✅ Símbolos UNICODE directos: ≤ ≥ ≠ ∞ ± × ÷ √ π ∑ ∫ ∂ λ μ ρ σ
  ✅ Subíndices con guion bajo simple: x_1, x_2 (NO x_{{1}})
  ✅ Potencias con ^: x^2, e^x, Q^2
  ✅ Multiplicación: usa * o yuxtaposición (2x_1, NO 2 \\cdot x_1)
  ✅ Fracciones inline: 1000/x (NO \\frac{{1000}}{{x}})
  ✅ Listas con guiones - o números 1. 2. 3.
  ✅ Separadores con líneas de === o ---

EJEMPLO DEL ESTILO ESPERADO:

  ============================================
   1. IDENTIFICACIÓN DEL PROBLEMA
  ============================================
  Es un problema de tipo NLP (programación no lineal) porque la
  función objetivo contiene el término cuadrático -0.01·Q^2.

  ============================================
   2. VARIABLES DE DECISIÓN
  ============================================
  Q = cantidad de unidades producidas y vendidas (unidades)
  P = precio de venta por unidad ($/unidad), función de Q
  Z = beneficio total ($)

  ============================================
   3. FORMULACIÓN MATEMÁTICA
  ============================================
  Maximizar:  Z(Q) = P(Q)·Q - C(Q)
              Z(Q) = (100 - 0.01Q)·Q - (50Q + 10000)
              Z(Q) = -0.01Q^2 + 50Q - 10000

  Sujeto a:   Q ≥ 0

  ============================================
   4. MÉTODO DE RESOLUCIÓN
  ============================================
  Como Z(Q) es una parábola que abre hacia abajo (coeficiente
  cuadrático negativo), el máximo se obtiene con la condición
  de primer orden:
        dZ/dQ = -0.02Q + 50 = 0
        Q* = 2500

  ============================================
   5. SOLUCIÓN ÓPTIMA E INTERPRETACIÓN
  ============================================
  Q* = 2500 unidades
  P* = 100 - 0.01(2500) = 75 $/unidad
  Z* = -0.01(2500)^2 + 50(2500) - 10000 = 52500 $

INSTRUCCIONES DE CONTENIDO:

1. Identifica el tipo de problema. Si crees que el clasificador se equivocó, dilo.
2. Define cada variable con su unidad física exacta.
3. Escribe la formulación matemática completa en texto plano.
4. Nombra el algoritmo apropiado (Simplex, Húngaro, Dijkstra, derivadas, EOQ, etc).
5. Si arriba aparece "SOLUCIÓN NUMÉRICA EXACTA", úsala TAL CUAL — no recalcules.
6. Si no hay solución exacta, calcula paso a paso con álgebra explícita.
7. Identifica restricciones activas (limitantes) e inactivas (sobrantes).
8. Interpreta el significado económico/práctico de la solución.
9. Verifica al final sustituyendo la solución en cada restricción original.
10. Sé conciso pero completo. NO uses LaTeX. NO trunques tu respuesta.
"""


# =============================================================
# PIPELINE PRINCIPAL CON SELF-CONSISTENCY
# =============================================================

@dataclass
class ResultadoIO:
    pregunta: str
    tipo: str
    respuesta: str
    desde_cache: bool = False
    solucion_exacta: str = ""
    intentos: int = 1


# =============================================================
# LIMPIADOR DE LaTeX → texto plano
# =============================================================

def limpiar_latex(texto: str) -> str:
    """
    Convierte LaTeX a texto plano legible en terminal.
    Aplica una serie de sustituciones para los comandos más comunes.
    """
    if not texto:
        return texto

    # Bloques matemáticos: quitar delimitadores pero mantener contenido
    texto = re.sub(r'\\\[(.*?)\\\]', r'\1', texto, flags=re.DOTALL)
    texto = re.sub(r'\\\((.*?)\\\)', r'\1', texto, flags=re.DOTALL)
    texto = re.sub(r'\$\$(.*?)\$\$', r'\1', texto, flags=re.DOTALL)
    texto = re.sub(r'\$([^$\n]+?)\$', r'\1', texto)

    # \frac{a}{b} → (a)/(b)  — aplicado dos veces por anidación simple
    for _ in range(2):
        texto = re.sub(r'\\frac\{([^{}]+)\}\{([^{}]+)\}', r'(\1)/(\2)', texto)

    # \sqrt{x} → √(x)
    texto = re.sub(r'\\sqrt\{([^{}]+)\}', r'√(\1)', texto)
    texto = re.sub(r'\\sqrt\[(\d+)\]\{([^{}]+)\}', r'(\2)^(1/\1)', texto)

    # Símbolos griegos y operadores
    sustituciones = {
        r'\\cdot\b': '·',
        r'\\times\b': '×',
        r'\\div\b': '÷',
        r'\\pm\b': '±',
        r'\\mp\b': '∓',
        r'\\le\b': '≤', r'\\leq\b': '≤',
        r'\\ge\b': '≥', r'\\geq\b': '≥',
        r'\\neq\b': '≠', r'\\ne\b': '≠',
        r'\\approx\b': '≈',
        r'\\equiv\b': '≡',
        r'\\infty\b': '∞',
        r'\\partial\b': '∂',
        r'\\nabla\b': '∇',
        r'\\sum\b': '∑',
        r'\\prod\b': '∏',
        r'\\int\b': '∫',
        r'\\to\b': '→',
        r'\\Rightarrow\b': '⇒',
        r'\\Leftarrow\b': '⇐',
        r'\\Leftrightarrow\b': '⇔',
        r'\\rightarrow\b': '→',
        r'\\leftarrow\b': '←',
        r'\\in\b': '∈',
        r'\\notin\b': '∉',
        r'\\subset\b': '⊂',
        r'\\subseteq\b': '⊆',
        r'\\cup\b': '∪',
        r'\\cap\b': '∩',
        r'\\forall\b': '∀',
        r'\\exists\b': '∃',
        # Letras griegas
        r'\\alpha\b': 'α', r'\\beta\b': 'β', r'\\gamma\b': 'γ',
        r'\\delta\b': 'δ', r'\\epsilon\b': 'ε', r'\\varepsilon\b': 'ε',
        r'\\zeta\b': 'ζ', r'\\eta\b': 'η', r'\\theta\b': 'θ',
        r'\\iota\b': 'ι', r'\\kappa\b': 'κ', r'\\lambda\b': 'λ',
        r'\\mu\b': 'μ', r'\\nu\b': 'ν', r'\\xi\b': 'ξ',
        r'\\pi\b': 'π', r'\\rho\b': 'ρ', r'\\sigma\b': 'σ',
        r'\\tau\b': 'τ', r'\\upsilon\b': 'υ', r'\\phi\b': 'φ',
        r'\\chi\b': 'χ', r'\\psi\b': 'ψ', r'\\omega\b': 'ω',
        r'\\Gamma\b': 'Γ', r'\\Delta\b': 'Δ', r'\\Theta\b': 'Θ',
        r'\\Lambda\b': 'Λ', r'\\Xi\b': 'Ξ', r'\\Pi\b': 'Π',
        r'\\Sigma\b': 'Σ', r'\\Phi\b': 'Φ', r'\\Psi\b': 'Ψ',
        r'\\Omega\b': 'Ω',
        # Funciones (las dejamos sin barra)
        r'\\max\b': 'max', r'\\min\b': 'min',
        r'\\sup\b': 'sup', r'\\inf\b': 'inf',
        r'\\log\b': 'log', r'\\ln\b': 'ln', r'\\exp\b': 'exp',
        r'\\sin\b': 'sin', r'\\cos\b': 'cos', r'\\tan\b': 'tan',
        r'\\arcsin\b': 'arcsin', r'\\arccos\b': 'arccos', r'\\arctan\b': 'arctan',
        # Tipografía: quitar el comando, mantener contenido
        r'\\text\{([^{}]+)\}': r'\1',
        r'\\textbf\{([^{}]+)\}': r'\1',
        r'\\textit\{([^{}]+)\}': r'\1',
        r'\\mathrm\{([^{}]+)\}': r'\1',
        r'\\mathbf\{([^{}]+)\}': r'\1',
        r'\\mathit\{([^{}]+)\}': r'\1',
        r'\\boldsymbol\{([^{}]+)\}': r'\1',
        r'\\operatorname\{([^{}]+)\}': r'\1',
        # Espaciado
        r'\\,': ' ', r'\\;': ' ', r'\\:': ' ', r'\\!': '',
        r'\\quad\b': '   ', r'\\qquad\b': '      ',
        r'\\ ': ' ',
        # Llaves izq/der invisibles
        r'\\left\b': '', r'\\right\b': '',
        # Saltos de línea LaTeX
        r'\\\\': '\n',
        # Entornos: align, cases, equation, gather, etc.
        r'\\begin\{[^{}]+\}': '',
        r'\\end\{[^{}]+\}': '',
        # Caracteres escapados
        r'\\&': '&', r'\\%': '%', r'\\#': '#', r'\\\$': '$',
        r'\\_': '_',
    }
    for patron, reemplazo in sustituciones.items():
        texto = re.sub(patron, reemplazo, texto)

    # Subíndices y superíndices con llaves: x_{1} → x_1 ; x^{2} → x^2
    texto = re.sub(r'_\{([^{}]+)\}', r'_\1', texto)
    texto = re.sub(r'\^\{([^{}]+)\}', r'^\1', texto)

    # Limpiar espacios y saltos de línea redundantes
    texto = re.sub(r'[ \t]+\n', '\n', texto)
    texto = re.sub(r'\n[ \t]+\n', '\n\n', texto)
    texto = re.sub(r'\n{3,}', '\n\n', texto)

    return texto.strip()


def preguntar_io(pregunta: str, df_libro: pd.DataFrame,
                 guardar: bool = True, self_consistency: bool = False) -> ResultadoIO:
    """
    Pipeline de resolución desde cero:
      1. ¿Es exactamente la misma pregunta de hace rato? → respuesta cacheada
      2. Clasificar tipo
      3. Resolver numéricamente con solver determinístico (si aplica)
      4. Buscar teoría del libro Hillier
      5. Llamar al LLM para que EXPLIQUE (1 vez o N con voto)
      6. Guardar al historial (NO se usa para RAG)
    """
    # 1. Caché de exactitud (sim ≥ 0.99)
    en_cache, resp_cache = respuesta_en_cache(pregunta)
    if en_cache:
        print(f"⚡ Pregunta repetida (sim ≥ {UMBRAL_CACHE}) — devolviendo respuesta previa")
        return ResultadoIO(pregunta=pregunta, tipo="CACHE",
                           respuesta=resp_cache, desde_cache=True)

    # 2. Clasificar
    print("🔎 Clasificando tipo de problema...")
    tipo = clasificar_problema(pregunta)
    print(f"📌 Tipo detectado: {tipo}")

    # 3. Resolver numéricamente
    print("🧮 Intentando resolver con solver determinístico...")
    solucion_exacta, tipo = resolver_numericamente(pregunta, tipo)
    if solucion_exacta:
        print(f"✅ Solver numérico tuvo éxito ({tipo})")
    else:
        print(f"ℹ️  Sin solver para {tipo} — el LLM razonará desde cero")

    # 4. Teoría del libro Hillier
    print("📚 Buscando teoría relevante en Hillier...")
    teoria = buscar_teoria(pregunta, df_libro, k=K_TEORIA) if not df_libro.empty else ""
    print(f"   - Chunks de teoría recuperados: {K_TEORIA if teoria else 0}")

    # 5. Construir prompt + invocar
    prompt = construir_prompt(pregunta, tipo, solucion_exacta, teoria)

    if self_consistency and not solucion_exacta:
        # Voto solo si el solver no respondió (riesgo alto de error)
        print(f"🗳️  Self-consistency: {NUM_MUESTRAS} muestreos con voto...")
        muestras = []
        for i in range(NUM_MUESTRAS):
            llm = llm_reasoning(temperature=0.3)
            try:
                r = con_retry(_invoke, llm, prompt, etiqueta=f"reasoning-{i}")
                muestras.append(r)
            except Exception as e:
                print(f"⚠️  Muestra {i} falló: {e}")
        respuesta_final = elegir_mejor_muestra(muestras) if muestras else "❌ Todas las muestras fallaron"
    else:

        if solucion_exacta:
          llm = ChatGroq(
                model=MODEL_REASONING,
                temperature=0.1,
                api_key=GROQ_API_KEY,
                reasoning_effort="low",   # bajo effort, suficiente para explicar
                max_tokens=4096,
            )
        else:
          llm = llm_reasoning(temperature=0.1)
        respuesta_final = con_retry(_invoke, llm, prompt, etiqueta="reasoning")

    # Aplicar limpieza de LaTeX residual ANTES de concatenar la solución exacta
    respuesta_final = limpiar_latex(respuesta_final)

    # Concatenar solución exacta arriba
    if solucion_exacta:
        respuesta_final = (
            solucion_exacta + "\n\n" + "=" * 60 +
            "\n  EXPLICACIÓN DETALLADA:\n" + "=" * 60 + "\n" + respuesta_final
        )

    # 6. Guardar SOLO en historial — pero NO si la respuesta tiene errores
    respuesta_es_fallida = (
        "❌" in respuesta_final[:500]
        or "scipy.linprog error" in respuesta_final
        or "Invalid input for linprog" in respuesta_final
        or "no convergió" in respuesta_final.lower()
        or "Todas las muestras fallaron" in respuesta_final
        or "estructura inconsistente" in respuesta_final
    )
    if guardar and not respuesta_es_fallida:
        guardar_ejercicio(pregunta, respuesta_final, tipo)
        print(f"💾 Guardado en historial como tipo={tipo}")
    elif respuesta_es_fallida:
        print("🚫 Respuesta con errores — NO se guarda en historial")

    return ResultadoIO(
        pregunta=pregunta, tipo=tipo, respuesta=respuesta_final,
        desde_cache=False, solucion_exacta=solucion_exacta,
    )


def elegir_mejor_muestra(muestras: list[str]) -> str:
    """
    Voto simple: extrae números clave (Z = ...) de cada muestra y vota
    el más frecuente. Devuelve la muestra que contiene el resultado mayoritario.
    """
    if len(muestras) == 1:
        return muestras[0]

    # Extraer "Z = NUMERO" o "= NUMERO" de cada muestra
    votos = []
    for m in muestras:
        nums = re.findall(r'Z\s*[=≈]\s*([+-]?\d+(?:\.\d+)?)', m)
        if not nums:
            nums = re.findall(r'óptim[oa][^.]*?([+-]?\d+(?:\.\d+)?)', m, re.IGNORECASE)
        votos.append(nums[0] if nums else None)

    contador = Counter(v for v in votos if v is not None)
    if not contador:
        return max(muestras, key=len)  # la más larga como fallback

    ganador, _ = contador.most_common(1)[0]
    for muestra, voto in zip(muestras, votos):
        if voto == ganador:
            return muestra
    return muestras[0]


# =============================================================
# CLI
# =============================================================

MENU = """
╔══════════════════════════════════════════════╗
║      SISTEMA DE INVESTIGACIÓN DE             ║
║      OPERACIONES — v5 (texto plano)          ║
╠══════════════════════════════════════════════╣
║  1. Resolver un nuevo ejercicio              ║
║  2. Consultar ejercicio guardado por ID      ║
║  3. Ver últimos 10 ejercicios resueltos      ║
║  4. Ver estadísticas de la base              ║
║  5. Resolver con self-consistency (lento)    ║
║  6. Salir                                    ║
╚══════════════════════════════════════════════╝
"""


def listar_recientes(n: int = 10):
    res = (supabase.table(TABLA_EJERC)
           .select("id, pregunta, tipo, creado_at")
           .order("id", desc=True).limit(n).execute())
    if not res.data:
        print("No hay ejercicios guardados.")
        return
    print(f"\n{'ID':<6}{'TIPO':<14}{'PREGUNTA':<70}{'FECHA'}")
    print("-" * 110)
    for row in res.data:
        p = row['pregunta'][:65].replace('\n', ' ').replace('\r', ' ')
        f = (row.get('creado_at') or 'N/A')[:10]
        t = (row.get('tipo') or 'OTRO')[:12]
        print(f"{row['id']:<6}{t:<14}{p:<70}{f}")


def consultar_id():
    listar_recientes(10)
    try:
        eid = int(input("\nID a ver: ").strip())
        res = supabase.table(TABLA_EJERC).select("pregunta, respuesta, tipo").eq("id", eid).execute()
        if res.data:
            r = res.data[0]
            print(f"\n📋 PREGUNTA ({r.get('tipo','OTRO')}):\n{r['pregunta']}")
            print(f"\n💡 RESPUESTA:\n{r['respuesta']}")
        else:
            print("ID no encontrado.")
    except ValueError:
        print("ID inválido.")


def estadisticas():
    res = supabase.table(TABLA_EJERC).select("tipo").execute()
    if not res.data:
        print("Base vacía.")
        return
    cont = Counter(r.get("tipo", "OTRO") for r in res.data)
    print("\n=== Distribución por tipo de problema ===")
    for t, c in sorted(cont.items(), key=lambda x: -x[1]):
        print(f"  {t:<14} {c:>4}")
    print(f"  {'TOTAL':<14} {sum(cont.values()):>4}")


def loop_principal(df_libro: pd.DataFrame):
    while True:
        print(MENU)
        op = input("Opción (1-6): ").strip()

        if op == "1" or op == "5":
            print("\nPega tu ejercicio (FIN en línea nueva para terminar):")
            lineas = []
            while True:
                ln = input()
                if ln.strip().upper() == "FIN":
                    break
                lineas.append(ln)
            preg = "\n".join(lineas).strip()
            if not preg:
                print("Vacío.")
                continue
            print("\n🔍 Procesando...\n")
            resultado = preguntar_io(preg, df_libro,
                                     guardar=True,
                                     self_consistency=(op == "5"))
            print("\n" + "=" * 60)
            print(resultado.respuesta)
            print(f"\n📊 Tipo: {resultado.tipo}")

        elif op == "2":
            consultar_id()
        elif op == "3":
            listar_recientes(10)
        elif op == "4":
            estadisticas()
        elif op == "6":
            print("👋 Hasta luego.")
            break
        else:
            print("Opción inválida (1-6).")


# =============================================================
# ENTRY POINT
# =============================================================

if __name__ == "__main__":
    pdf_path = os.environ.get("PDF_PATH", "/content/Investigacion-Operaciones10Edicion-Frederick-S-Hillier (1).pdf")
    df_libro = asegurar_libro_indexado(pdf_path)
    print(f"\n📊 Estado: {ejercicios_count()} ejercicios en historial, {len(df_libro)} chunks de teoría")
    loop_principal(df_libro)